where = str(input("주소:"))
many = int(input("방의 개수:"))
price = int(input("가격:"))
print("주소: 서울시 종로구 \n방의 개수 : 3\n가격 : 100,000,000")
print("{}에 위치한 아주 좋은 아파트가 매물로 나왔습니다. 이 아파트는 {}개의 방을 가지고 있으며 가격은 {}입니다.".format(where,many,price))
